import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Daniel Bernal",
  description: "Generated By Brayan Daniel Bernal Lopez",
  icons: {
    icon: "/Logo-Daniel.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="scroll-smooth bg-black text-white">
        {children}
      </body>
    </html>
  );
}



